branch-defaults:
  CHEVRE-5:
    environment: chevre-api-dev
    group_suffix: null
  master:
    environment: chevre-api-dev
global:
  application_name: chevre_api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
